# Esse é um arquivo de configuração do Kubernetes que define um Service do tipo NodePort para expor um Deployment chamado "web".
# Ele cria um Service chamado "web-svc" que direciona o tráfego para os pods com o rótulo "app: web" na porta 80.

# 1) Service (web-svc)
# É o ponto fixo dentro do cluster. Ele recebe tráfego e distribui pros pods que têm o label app=web. 
# É uma abstração estável: os pods morrem e renascem, mas o Service continua com o mesmo IP interno.

# 2) Pods
# São as instâncias reais rodando o container. Cada um tem seu IP efêmero. O Service age como 
# “load balancer interno” e escolhe qual pod atender.


apiVersion: v1
kind: Service
metadata:
  name: web-svc
spec:
  selector:
    app: web
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080