# O QUE ESTÁ SENDO DEFINIDO AQUI?
# Este arquivo YAML define um cluster Kubernetes gerenciado pelo Cluster API usando o provider Docker. Logo, ele é usado PELO CAPI para criar um cluster Kubernetes "alvo" dentro de containers Docker.
# O arquivo define os seguintes recursos: 

# Cluster + DockerCluster                                           → descrevem o cluster alvo e a infraestrutura Docker.
# KubeadmControlPlane + DockerMachineTemplate                       → definem como nasce o control-plane.
# MachineDeployment + KubeadmConfigTemplate + DockerMachineTemplate → definem como nascem os nós workers.

# apiVersion  : define **qual versão da API** o recurso usa. O Cluster API lê isso para saber **como interpretar e validar** o objeto. Versões diferentes podem ter campos ou comportamentos distintos.  
# kind        : indica **o tipo exato de recurso** (Cluster, DockerCluster, KubeadmControlPlane, etc). O CAPI usa esse campo para **saber qual controlador** deve processar o objeto.  
# metadata    : traz informações de identificação (nome, namespace, rótulos, anotações). O CAPI usa isso para **indexar e rastrear** o recurso dentro do cluster de gerenciamento.  
# spec        : contém a **descrição desejada do recurso**. O CAPI lê este bloco para **gerar e reconciliar** a infraestrutura correspondente (máquinas, clusters, etc).  
# status      : (gerado automaticamente) mostra o **estado atual** observado pelo CAPI. É atualizado pelos controladores para refletir o progresso da criação ou reconciliação.  



# ============================================================
# 1. Definição do cluster lógico
# Aqui estamos definindo um recurso do tipo 'Cluster' que representa o cluster Kubernetes lógico que queremos criar. Sem ele, nada mais funciona.
# Esse recurso 'Cluster' define o nome do cluster, a rede de pods, e referencia os recursos que definem o control-plane e a infraestrutura onde o
# cluster será criado. Toda a definição do cluster (nós, control-plane, etc) está ligada a esse recurso 'Cluster' via o campo 'clusterName' em outros recursos.
# ============================================================
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: capi-docker-cluster
spec:
  clusterNetwork:                  # Define a rede de pods
    pods:
      cidrBlocks: ["192.168.0.0/16"]
  infrastructureRef:               # Aponta para o recurso de infraestrutura
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: DockerCluster
    name: capi-docker-cluster

---
# ============================================================
# 2. Definição da infraestrutura
# Aqui estamos definindo um recurso do tipo 'DockerCluster' que representa a infraestrutura Docker onde o cluster lógico definido acima será criado.
# A definição de cima só diz que queremos um cluster chamado 'capi-docker-cluster' e as especificações de rede. Mas não diz onde esse cluster vai existir.
# Este recurso 'DockerCluster' diz que o cluster será criado dentro de containers Docker na máquina física onde o Cluster API está rodando. O controller
# do provider-docker irá observar este recurso e criar os containers Docker necessários.
# ============================================================
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerCluster
metadata:
  name: capi-docker-cluster

---
# ============================================================
# 3. Definição do control-plane
# Aqui estamos definindo um recurso do tipo 'KubeadmControlPlane' que será do tipo (kind) 'KubeadmControlPlane', ou seja, um control-plane gerenciado via kubeadm.
# Esse recurso define quantos nós de control-plane queremos, a versão do Kubernetes, o template de máquina Docker para os nós do control-plane, e as configurações
# passadas ao kubeadm.
# ============================================================
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: capi-control-plane
spec:
  replicas: 1                # Número de nós de control-plane
  version: v1.30.0           # Versão do Kubernetes do cluster alvo
  infrastructureTemplate:    # Molde de máquina para o control-plane
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: DockerMachineTemplate
    name: capi-control-plane-template
  kubeadmConfigSpec:         # Configurações passadas ao kubeadm
    clusterConfiguration:
      apiServer: {}
      controllerManager: {}
      scheduler: {}
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cgroup-driver: cgroupfs

---
# ============================================================
# Template de máquina Docker para os nós do control-plane. 
# Ele será referenciado pelo recurso KubeadmControlPlane acima toda vez que um novo nó de control-plane for criado. Os nós são criados como containers Docker 
# na máquina física onde o Cluster API está rodando, mas no nosso caso ele criará remotamente pois o cluster será usado para gerenciar outro cluster (cluster alvo).
# ============================================================
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerMachineTemplate
metadata:
  name: capi-control-plane-template
spec:
  template:
    spec: {}

---
# ============================================================
# 4. Definição dos workers
# ============================================================
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: capi-worker-deployment
spec:
  replicas: 1                 # Número de nós worker
  clusterName: capi-docker-cluster
  selector:
    matchLabels: {}
  template:
    spec:
      version: v1.30.0
      bootstrap:
        configRef:            # Configuração de bootstrap para os workers
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: capi-worker-bootstrap
      infrastructureRef:      # Template de máquina Docker para os workers
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: DockerMachineTemplate
        name: capi-worker-template

---
# Configuração de bootstrap para workers (via kubeadm)
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: capi-worker-bootstrap
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cgroup-driver: cgroupfs

---
# Template de máquina Docker para os workers
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerMachineTemplate
metadata:
  name: capi-worker-template
spec:
  template:
    spec: {}
